remote_theme: brianmaierjr/uni
title: "План чтения Библии за год"

# Description of your website. This is used for social sharing.
description:  "Скачать план чтения Библии за год. В предлагаемом плане Ветхий и Новый заветы читаются параллельно. Ссылки для скачивания файлов для печати (в формате PDF)"

# A brief blurb about yourself
content: "В предлагаемом плане Ветхий и Новый заветы читаются параллельно. Доступны три варианта плана для печати (в формате PDF):"

# Add your social links
social:
  - platform: Обычный
    url: ./commonplan.pdf
  - platform: "Крупным шрифтом"
    url: ./eldersplan.pdf
  - platform: Молодёжный
    url: ./youthplan.pdf

# General settings
url: https://novchurch.github.io/plan
baseurl: "/plan" 
markdown: kramdown
sharing_image: half-sm.jpg
# google_analytics: "UA-58263416-1" # google analytics tracking

#### LAYOUT OPTIONS #####

# Half layout
half_side: right

# Full layout
full_text_position: right # left, right or center
