name: Build LaTeX document
on:
  push:
    paths:
      - 'download/**.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: download
          root_file: |
            plan10.tex
      - name: Download PDF
        uses: actions/download-artifact@v2
        with:
          name: plan10.pdf
          path: download/plan10.pdf 
