name: Build LaTeX document
on:
  push:
    paths:
      - 'download/**.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: download
          root_file: |
            plan10.tex
            commonplan.tex
            eldersplan.tex
            youthplan.tex
      - name: Upload plan10.pdf
        uses: actions/upload-artifact@v2
        with:
          name: plan10.pdf
          path: download/plan10.pdf
      - name: Upload commonplan.pdf
        uses: actions/upload-artifact@v2
        with:
          name: commonplan.pdf
          path: download/commonplan.pdf
      - name: Upload eldersplan.pdf
        uses: actions/upload-artifact@v2
        with:
          name: eldersplan.pdf
          path: download/eldersplan.pdf
      - name: Upload youthplan.pdf
        uses: actions/upload-artifact@v2
        with:
          name: youthplan.pdf
          path: download/youthplan.pdf
      - name: Release plan10.pdf
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: download/plan10.pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release commonplan.pdf
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: download/commonplan.pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release eldersplan.pdf
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: download/eldersplan.pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release youthplan.pdf
        uses: fnkr/github-action-ghr@v1
        env:
          GHR_PATH: download/youthplan.pdf
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
