name: Build LaTeX document and push the compiled PDF back to GitHub
on:
  push:
    paths:
      - 'download/**.tex'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    env:
      MANUSCRIPT_PATH: download/plan10 # exclude the '.tex' / '.pdf' extension!
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          working_directory: download
          root_file: |
            plan10.tex
            commonplan.tex
            eldersplan.tex
            youthplan.tex
      - name: Push PDFs
        run: |
          git checkout --orphan ${GITHUB_REF##*/}-pdf
          git rm -rf .github/
          cd download
          git rm -rf . 
          git add -f plan10.pdf commonplan.pdf eldersplan.pdf youthplan.pdf
          git -c user.name='paper-maker' -c user.email='paper-maker' commit -m "update pdf"
          git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}-pdf
