on: [push]

jobs:
  build-resume:
    runs-on: ubuntu-latest
    name: Create document
    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - uses: actions/checkout@v1
    - name: Install cyrillic
      run: |
        sudo apt-get install texlive-lang-cyrillic
    - name: Convert to pdf
      id: convert-to-pdf
      uses: closoco/pdflatex-action@v1.1.0
      with:
        texFile: download/commonplan.tex
    - name: Store pdf
      uses: actions/upload-artifact@v2
      with:
        name: plan.pdf
        path: plan.pdf
